#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true

#BSPWM coloring
bspc config normal_border_color		"#000000"
bspc config active_border_color		"#000000"
bspc config focused_border_color	"#ff0000"
#bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

numlockx on &
vmware-user-suid-wrapper &
$HOME/.config/polybar/launch.sh
nitrogen --restore &
killall volumeicon
volumeicon &
picom &
nm-applet &
caprine &
